name: trans_slim
channels:
  - anaconda
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - attrs=23.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - importlib_resources=6.1.0
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libsqlite=3.43.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.3
  - ncurses=6.4
  - networkx=2.7.1
  - numpy=1.26.0
  - openssl=3.1.3
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - pyparsing=3.1.1
  - python=3.12.0
  - python_abi=3.12
  - readline=8.2
  - referencing=0.30.2
  - rpds-py=0.10.6
  - setuptools=68.2.2
  - svgwrite=1.4.3
  - tk=8.6.13
  - tskit=0.5.6
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.2.6
  - zipp=3.17.0
  - pytest=7.4.3