package:
  name: enivol-test
  version: 0.0.1
  description: An epi-evo simulator for infectious disease outbreak
  license: GNU
  maintainers:
    - Perry Xu
    - Shenni Liang
    - Jae Hahn
    - Vivian Zhao
  # Add additional metadata as needed

source:
  path: ./

requirements:
  build:
    - python
    - pip
    - setuptools
    # - r-base
    - slim
    # - numpy-base
  run:
    - python >=3.10.13
    - matplotlib >=3.8.2
    - pandas >=2.2.0
    - ete3 >=3.1.3
    - numpy >=1.26.0
    - numpy-base >=1.26.0
    - tskit >=0.5.6
    - pyslim >=1.0.4
    - r-base >=4.3.2
    - r-ape >=5.7
    - r-phylobase >=0.8.12
    - bioconductor-ggtree >=3.10.0
    - r-ggplot2 >=3.4.4
    - slim ==4.0.1
    # Add any other runtime dependencies here

build:
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

test:
  imports:
    - enivol

about:
  home: https://github.com/EpiEvoSoftware/original_pipeline
  summary: A brief summary of my package.
  description: |
    A longer description of my package.
    This can span multiple lines.
  license: GNU