name: Python Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: trans_slim
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name trans_slim

    - name: Run tests
      run: |
        conda activate trans_slim
        cd codes/test
        pytest

