name: Python Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: your-environment-name

    - name: Install Dependencies
      run: |
        conda env update --file environment.yml --name your-environment-name

    - name: Run tests
      run: |
        conda activate your-environment-name
        cd codes/test
        pytest
