name: Python Tests


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        activate-environment: e3SIM_linux
        environment-file: e3SIM_linux.yml
        auto-activate-base: false

    - name: Run Pytest
      shell: bash -l {0}
      run: |
        conda activate e3SIM_linux
        cd test


